#!/usr/bin/env bash
# uninstall-mac.sh — remove the Brain wiring from a Claude Code config dir on macOS.
#
# DEPRECATED (2026-08-25) — use brain-uninstall.py.
#
#     python3 <repo>/brain-uninstall.py <claude-config-dir>
#
# brain-uninstall.py is the cross-platform inverse of brain-setup.py, the installer
# this repo's docs and CLAUDE.md point at. It prunes the same Brain-owned hook and
# permission entries through the same brain_settings_merge.py, so it shares the one
# ownership predicate — which is the whole reason install and uninstall must stay
# symmetric. Keeping four of each is what let the permissions.allow rule be written
# by the installers on 2026-07-28 and removed by none of them until 2026-08-24.
#
# uninstall-mac.sh still works and still removes a Brain install correctly. It will
# not receive new behaviour. See ROADMAP 'Retire the platform-specific installers'.
#
# Usage:
#     ~/src/Ai-Brain/uninstall-mac.sh <claude-config-dir>
#
# Examples:
#     ~/src/Ai-Brain/uninstall-mac.sh ~/.claude
#     ~/src/Ai-Brain/uninstall-mac.sh ~/.claude-personal
#     ~/src/Ai-Brain/uninstall-mac.sh ~/.claude-work
#
# Reverses setup-mac.sh. Idempotent: running on a never-installed dir is a no-op.
#
# WHAT THIS TOUCHES
#   - unregisters the 'brain' user-scope MCP server from this config dir
#   - prunes Brain-owned entries from <config>/settings.json
#   - removes <config>/CLAUDE.md ONLY if it carries our managed-by marker
#     (hand-edited CLAUDE.md without the marker is left alone)
#   - removes <config>/skills/brain/ (leaves <config>/skills/ for other skills)
#   - removes <repo>/mcp-server/.venv (regenerated by re-running setup)
#
# WHAT THIS DOES NOT TOUCH
#   - the vault (Brain/user, feedback, projects, sessions, activity.md, index)
#   - ~/.cache/fastembed (shared OS-wide, harmless)
#   - the repo itself

set -euo pipefail

if [ $# -lt 1 ]; then
  echo "usage: $0 <claude-config-dir>" >&2
  echo "example: $0 ~/.claude-personal" >&2
  exit 1
fi

CLAUDE_DIR="${1/#\~/$HOME}"
REPO_DIR="$(cd "$(dirname "$0")" && pwd)"

# A header comment nobody reads is exactly the red herring deprecating this is meant
# to remove, so say it on stderr where the operator is actually looking. Warn only --
# this script still works, and failing an install over a deprecation would be worse
# than the duplication it is meant to retire.
echo "" >&2
echo "WARNING: uninstall-mac.sh is DEPRECATED and no longer receives new behaviour." >&2
echo "         Use the cross-platform uninstaller instead:" >&2
echo "           python3 \"$REPO_DIR/brain-uninstall.py\" \"$CLAUDE_DIR\"" >&2
echo "         Continuing anyway in 3s (Ctrl-C to abort)..." >&2
echo "" >&2
sleep 3
MCP_SERVER_DIR="$REPO_DIR/mcp-server"
VENV_DIR="$MCP_SERVER_DIR/.venv"
VENV_PYTHON="$VENV_DIR/bin/python"

# Prefer the in-repo venv python for the settings-merge script (it's the same one
# that wrote the file), but fall back to system python3 if the venv is already
# gone — the prune logic only needs stdlib json.
PY_FOR_PRUNE="$VENV_PYTHON"
if [ ! -x "$PY_FOR_PRUNE" ]; then
  if command -v python3 >/dev/null 2>&1; then
    PY_FOR_PRUNE="$(command -v python3)"
  else
    PY_FOR_PRUNE=""
  fi
fi

echo "Brain uninstall"
echo "  repo:         $REPO_DIR"
echo "  config dir:   $CLAUDE_DIR"
if [ ! -d "$CLAUDE_DIR" ]; then
  echo
  echo "NOTE: $CLAUDE_DIR does not exist — nothing to uninstall from there."
  echo "      (venv removal below still runs.)"
fi
echo

# 1. Unregister the MCP server via the claude CLI (same config-dir asymmetry as install).
echo "[1/5] unregistering brain MCP server (user scope)"
CLAUDE_BIN="${CLAUDE_BIN:-claude}"
_canonical_path() {
  if [ -d "$1" ]; then ( cd "$1" && pwd -P ); else printf '%s' "${1%/}"; fi
}
if [ "$(_canonical_path "$CLAUDE_DIR")" = "$(_canonical_path "$HOME/.claude")" ]; then
  IS_DEFAULT_TARGET=1
else
  IS_DEFAULT_TARGET=0
fi
claude_cli() {
  if [ "$IS_DEFAULT_TARGET" = "1" ]; then
    "$CLAUDE_BIN" "$@"
  else
    CLAUDE_CONFIG_DIR="$CLAUDE_DIR" "$CLAUDE_BIN" "$@"
  fi
}

if ! command -v "$CLAUDE_BIN" >/dev/null 2>&1; then
  echo "       ⚠ '$CLAUDE_BIN' not on PATH — skipping MCP unregister."
  echo "         If brain is still registered, remove it manually later:"
  if [ "$IS_DEFAULT_TARGET" = "1" ]; then
    echo "           $CLAUDE_BIN mcp remove brain --scope user"
  else
    echo "           CLAUDE_CONFIG_DIR=$CLAUDE_DIR $CLAUDE_BIN mcp remove brain --scope user"
  fi
else
  # `remove` is idempotent at the CLI level — exits non-zero if not present, which
  # we treat as success. Keep stderr for anything genuinely unexpected.
  if claude_cli mcp remove brain --scope user >/dev/null 2>&1; then
    echo "       ✓ brain MCP server unregistered"
  else
    echo "       (brain was not registered; nothing to remove)"
  fi
fi

# 2. Prune Brain-owned entries from settings.json via the shared
#    brain_settings_merge.py — the SAME module (and therefore the same ownership
#    predicate) the installers use. An asymmetry here means either orphan hooks
#    left after uninstall or duplicated hooks after the next install. Third-party
#    hooks registered for the same events are left untouched, and an unparseable
#    settings.json is left exactly as found.
SETTINGS_FILE="$CLAUDE_DIR/settings.json"
echo "[2/5] pruning Brain hooks from $SETTINGS_FILE"
if [ ! -f "$SETTINGS_FILE" ]; then
  echo "       (no settings.json — nothing to prune)"
elif [ -z "$PY_FOR_PRUNE" ]; then
  echo "       ⚠ no python3 available to parse settings.json — leaving hooks in place." >&2
  echo "         Install Python 3 and re-run, or hand-edit $SETTINGS_FILE." >&2
else
  "$PY_FOR_PRUNE" "$REPO_DIR/brain_settings_merge.py" prune \
    --settings "$SETTINGS_FILE" \
    --brain-hooks "$REPO_DIR/hooks"
fi

# 3. Delete CLAUDE.md only if it carries our managed-by marker. Hand-edited
#    CLAUDE.md without the marker is left alone — the user may have added agent
#    instructions or notes since install.
MARKER='<!-- managed-by: ai-brain -->'
CLAUDE_MD="$CLAUDE_DIR/CLAUDE.md"
echo "[3/5] checking $CLAUDE_MD"
if [ ! -f "$CLAUDE_MD" ]; then
  echo "       (no CLAUDE.md to remove)"
elif head -n 5 "$CLAUDE_MD" | grep -Fq "$MARKER"; then
  rm -f "$CLAUDE_MD"
  echo "       ✓ removed (marker present)"
else
  echo "       ⚠ CLAUDE.md has no managed-by marker — leaving it in place."
  echo "         (If you want it gone, delete it manually: rm '$CLAUDE_MD')"
fi

# 4. Remove the brain skill, but NOT the parent skills/ directory (it may host
#    other skills the user added outside of this installer's scope).
SKILL_DIR="$CLAUDE_DIR/skills/brain"
echo "[4/5] removing $SKILL_DIR"
if [ -d "$SKILL_DIR" ]; then
  rm -rf "$SKILL_DIR"
  echo "       ✓ removed"
  # If skills/ is now empty, tidy it up too.
  if [ -d "$CLAUDE_DIR/skills" ] && [ -z "$(ls -A "$CLAUDE_DIR/skills" 2>/dev/null || true)" ]; then
    rmdir "$CLAUDE_DIR/skills" 2>/dev/null || true
  fi
else
  echo "       (not present)"
fi

# 5. Remove the in-repo venv — but only if no OTHER claude config dir still
#    references it. The venv is shared across every config dir setup installed
#    into; if the user has ~/.claude-personal AND ~/.claude-work, uninstalling
#    from one must not break the other.
#    The installer writes the venv path literally into each config's settings.json,
#    so a substring grep catches every live reference.
echo "[5/5] removing $VENV_DIR"
if [ ! -d "$VENV_DIR" ]; then
  echo "       (not present)"
else
  STILL_USED=""
  for other in "$HOME"/.claude*; do
    [ -d "$other" ] || continue
    [ "$(_canonical_path "$other")" = "$(_canonical_path "$CLAUDE_DIR")" ] && continue
    if [ -f "$other/settings.json" ] && grep -Fq "$VENV_DIR" "$other/settings.json" 2>/dev/null; then
      STILL_USED="$other"
      break
    fi
  done
  if [ -n "$STILL_USED" ]; then
    echo "       (still referenced by $STILL_USED — leaving in place)"
    echo "       Run this script on $STILL_USED too if you want the venv gone."
  else
    rm -rf "$VENV_DIR"
    echo "       ✓ removed"
  fi
fi

echo
echo "✓ Brain uninstalled from $CLAUDE_DIR"
echo
echo "Not touched (by design):"
echo "  - your vault (Brain/user, feedback, projects, sessions, activity.md, .index/)"
echo "  - ~/.cache/fastembed (shared OS-wide embedding model cache)"
echo "  - this repo"
echo
echo "To reinstall later: $REPO_DIR/setup-mac.sh $CLAUDE_DIR <vault-path>"
