#!/usr/bin/env pwsh
# uninstall-windows.ps1 - remove the Brain wiring from a Claude Code config dir on Windows.
#
# DEPRECATED (2026-08-25) — use brain-uninstall.py.
#
#     python3 <repo>/brain-uninstall.py <claude-config-dir>
#
# brain-uninstall.py is the cross-platform inverse of brain-setup.py, the installer
# this repo's docs and CLAUDE.md point at. It prunes the same Brain-owned hook and
# permission entries through the same brain_settings_merge.py, so it shares the one
# ownership predicate — which is the whole reason install and uninstall must stay
# symmetric. Keeping four of each is what let the permissions.allow rule be written
# by the installers on 2026-07-28 and removed by none of them until 2026-08-24.
#
# uninstall-windows.ps1 still works and still removes a Brain install correctly. It will
# not receive new behaviour. See ROADMAP 'Retire the platform-specific installers'.
#
# Usage:
#     powershell -ExecutionPolicy Bypass -File C:\src\Ai-Brain\uninstall-windows.ps1 <claude-config-dir>
#
# Examples:
#     powershell -ExecutionPolicy Bypass -File C:\src\Ai-Brain\uninstall-windows.ps1 `
#         "$env:USERPROFILE\.claude"
#     powershell -ExecutionPolicy Bypass -File C:\src\Ai-Brain\uninstall-windows.ps1 `
#         "$env:USERPROFILE\.claude-personal"
#
# Reverses setup-windows.ps1. Idempotent: running on a never-installed dir is a no-op.
#
# WHAT THIS TOUCHES
#   - unregisters the 'brain' user-scope MCP server from this config dir
#   - prunes Brain-owned entries from <config>\settings.json
#   - removes <config>\CLAUDE.md ONLY if it carries our managed-by marker
#     (hand-edited CLAUDE.md without the marker is left alone)
#   - removes <config>\skills\brain\ (leaves <config>\skills\ for other skills)
#   - removes <config>\brain-launch.cmd (Windows-only generated wrapper)
#   - removes <repo>\mcp-server\.venv (regenerated by re-running setup)
#
# WHAT THIS DOES NOT TOUCH
#   - the vault (Brain\user, feedback, projects, sessions, activity.md, index)
#   - %LOCALAPPDATA%\fastembed_cache or the user's fastembed cache path
#   - the repo itself

[CmdletBinding()]
param(
  [Parameter(Mandatory=$true, Position=0)][string]$ClaudeDir
)

$ErrorActionPreference = 'Stop'

function Expand-UserPath([string]$p) {
  if ($p.StartsWith('~')) { $p = $p -replace '^~', $HOME }
  return [System.IO.Path]::GetFullPath($p)
}

$ClaudeDir    = Expand-UserPath $ClaudeDir
$RepoDir      = Split-Path -Parent $MyInvocation.MyCommand.Path

# A header comment nobody reads is exactly the red herring deprecating this is meant
# to remove, so say it where the operator is looking. Write-Warning, not a native
# write to stderr: $ErrorActionPreference = 'Stop' turns any native stderr into a
# terminating NativeCommandError under PS 5.1, and failing over a deprecation notice
# would be worse than the duplication it is meant to retire.
Write-Warning "uninstall-windows.ps1 is DEPRECATED and no longer receives new behaviour."
Write-Warning "Use the cross-platform uninstaller instead: python3 '$RepoDir\brain-uninstall.py' '$ClaudeDir'"
Write-Warning "Continuing anyway in 3s (Ctrl-C to abort)..."
Start-Sleep -Seconds 3
$McpServerDir = Join-Path $RepoDir 'mcp-server'
$VenvDir      = Join-Path $McpServerDir '.venv'
$VenvPython   = Join-Path $VenvDir 'Scripts\python.exe'

# Prefer the in-repo venv python for the settings-prune script; fall back to a
# system python on PATH if the venv is already gone. Only stdlib json needed.
$PyForPrune = $null
if (Test-Path $VenvPython) {
  $PyForPrune = $VenvPython
} else {
  foreach ($cand in @('py', 'python', 'python3')) {
    if (Get-Command $cand -ErrorAction SilentlyContinue) { $PyForPrune = $cand; break }
  }
}

Write-Host "Brain uninstall"
Write-Host "  repo:         $RepoDir"
Write-Host "  config dir:   $ClaudeDir"
if (-not (Test-Path $ClaudeDir)) {
  Write-Host ""
  Write-Host "NOTE: $ClaudeDir does not exist - nothing to uninstall from there."
  Write-Host "      (venv removal below still runs.)"
}
Write-Host ""

# 1. Unregister the MCP server via the claude CLI (same config-dir asymmetry as install).
Write-Host "[1/6] unregistering brain MCP server (user scope)"
$ClaudeBin = if ($env:CLAUDE_BIN) { $env:CLAUDE_BIN } else { 'claude' }
$DefaultClaudeDir = Join-Path $env:USERPROFILE '.claude'
$IsDefaultTarget = ([System.IO.Path]::GetFullPath($ClaudeDir).TrimEnd('\')) -ieq `
                   ([System.IO.Path]::GetFullPath($DefaultClaudeDir).TrimEnd('\'))

if (-not (Get-Command $ClaudeBin -ErrorAction SilentlyContinue)) {
  Write-Host "       [warn] '$ClaudeBin' not on PATH - skipping MCP unregister."
  Write-Host "         If brain is still registered, remove it manually later:"
  if ($IsDefaultTarget) {
    Write-Host "           Remove-Item Env:CLAUDE_CONFIG_DIR -ErrorAction SilentlyContinue"
  } else {
    Write-Host "           `$env:CLAUDE_CONFIG_DIR = '$ClaudeDir'"
  }
  Write-Host "           claude mcp remove brain --scope user"
} else {
  Remove-Item Env:CLAUDE_CONFIG_DIR -ErrorAction SilentlyContinue
  if (-not $IsDefaultTarget) { $env:CLAUDE_CONFIG_DIR = $ClaudeDir }
  try {
    & $ClaudeBin mcp remove brain --scope user 2>$null | Out-Null
    if ($LASTEXITCODE -eq 0) {
      Write-Host "       [ok] brain MCP server unregistered"
    } else {
      Write-Host "       (brain was not registered; nothing to remove)"
    }
  } finally {
    Remove-Item Env:CLAUDE_CONFIG_DIR -ErrorAction SilentlyContinue
  }
}

# 2. Prune Brain-owned entries from settings.json via the shared
#    brain_settings_merge.py - the SAME module (and therefore the same ownership
#    predicate) the installers use. An asymmetry here means either orphan hooks
#    left after uninstall or duplicated hooks after the next install. Third-party
#    hooks registered for the same events are left untouched, and an unparseable
#    settings.json is left exactly as found.
$SettingsFile = Join-Path $ClaudeDir 'settings.json'
Write-Host "[2/6] pruning Brain hooks from $SettingsFile"
if (-not (Test-Path $SettingsFile)) {
  Write-Host "       (no settings.json - nothing to prune)"
} elseif (-not $PyForPrune) {
  Write-Warning "no Python available to parse settings.json - leaving hooks in place."
  Write-Warning "Install Python 3 and re-run, or hand-edit $SettingsFile."
} else {
  $HooksDir    = Join-Path $RepoDir 'hooks'
  $PruneScript = Join-Path $RepoDir 'brain_settings_merge.py'
  # Same PS 5.1 trap as the `claude mcp remove` calls: $ErrorActionPreference='Stop'
  # turns any native stderr into a terminating NativeCommandError, and an uninstall
  # must never abort on a diagnostic.
  try {
    $pruneOutput = (& $PyForPrune $PruneScript prune `
        --settings $SettingsFile `
        --brain-hooks $HooksDir 2>&1 | Out-String)
  } catch {
    $pruneOutput = $_.Exception.Message
  }
  if ($pruneOutput.Trim()) { Write-Host $pruneOutput.Trim() }
}

# 3. Delete CLAUDE.md only if it carries our managed-by marker.
$Marker = '<!-- managed-by: ai-brain -->'
$ClaudeMd = Join-Path $ClaudeDir 'CLAUDE.md'
Write-Host "[3/6] checking $ClaudeMd"
if (-not (Test-Path $ClaudeMd)) {
  Write-Host "       (no CLAUDE.md to remove)"
} else {
  $head = Get-Content $ClaudeMd -TotalCount 5 -ErrorAction SilentlyContinue
  if ($head -and ($head -join "`n").Contains($Marker)) {
    Remove-Item -Force $ClaudeMd
    Write-Host "       [ok] removed (marker present)"
  } else {
    Write-Host "       [warn] CLAUDE.md has no managed-by marker - leaving it in place."
    Write-Host "         (If you want it gone, delete it manually: Remove-Item '$ClaudeMd')"
  }
}

# 4. Remove the brain skill, but NOT the parent skills\ directory.
$SkillDir = Join-Path $ClaudeDir 'skills\brain'
Write-Host "[4/6] removing $SkillDir"
if (Test-Path $SkillDir) {
  Remove-Item -Recurse -Force $SkillDir
  Write-Host "       [ok] removed"
  $SkillsRoot = Join-Path $ClaudeDir 'skills'
  if ((Test-Path $SkillsRoot) -and (-not (Get-ChildItem -Force $SkillsRoot -ErrorAction SilentlyContinue))) {
    Remove-Item -Force $SkillsRoot -ErrorAction SilentlyContinue
  }
} else {
  Write-Host "       (not present)"
}

# 5. Remove the generated brain-launch.cmd (Windows-only).
$LaunchCmd = Join-Path $ClaudeDir 'brain-launch.cmd'
Write-Host "[5/6] removing $LaunchCmd"
if (Test-Path $LaunchCmd) {
  Remove-Item -Force $LaunchCmd
  Write-Host "       [ok] removed"
} else {
  Write-Host "       (not present)"
}

# 6. Remove the in-repo venv - but only if no OTHER claude config dir still
#    references it. The venv is shared across every config dir setup installed
#    into; uninstalling from one must not break others. On Windows the venv path
#    lives inside each config's brain-launch.cmd (and via that, indirectly in
#    settings.json), so check both files.
Write-Host "[6/6] removing $VenvDir"
if (-not (Test-Path $VenvDir)) {
  Write-Host "       (not present)"
} else {
  $StillUsed = $null
  $claudeCandidates = Get-ChildItem -Path $env:USERPROFILE -Directory -Filter '.claude*' -ErrorAction SilentlyContinue
  foreach ($other in $claudeCandidates) {
    $otherFull = [System.IO.Path]::GetFullPath($other.FullName).TrimEnd('\')
    $selfFull  = [System.IO.Path]::GetFullPath($ClaudeDir).TrimEnd('\')
    if ($otherFull -ieq $selfFull) { continue }
    foreach ($probe in @((Join-Path $other.FullName 'settings.json'),
                         (Join-Path $other.FullName 'brain-launch.cmd'))) {
      if (Test-Path $probe) {
        $txt = Get-Content $probe -Raw -ErrorAction SilentlyContinue
        if ($txt -and ($txt -like "*$VenvDir*")) { $StillUsed = $other.FullName; break }
      }
    }
    if ($StillUsed) { break }
  }
  if ($StillUsed) {
    Write-Host "       (still referenced by $StillUsed - leaving in place)"
    Write-Host "       Run this script on $StillUsed too if you want the venv gone."
  } else {
    Remove-Item -Recurse -Force $VenvDir
    Write-Host "       [ok] removed"
  }
}

Write-Host ""
Write-Host "[ok] Brain uninstalled from $ClaudeDir"
Write-Host ""
Write-Host "Not touched (by design):"
Write-Host "  - your vault (Brain\user, feedback, projects, sessions, activity.md, .index\)"
Write-Host "  - the fastembed model cache (shared, harmless)"
Write-Host "  - this repo"
Write-Host ""
Write-Host "To reinstall later:"
Write-Host "  powershell -ExecutionPolicy Bypass -File '$RepoDir\setup-windows.ps1' '$ClaudeDir' '<vault-path>'"
