#!/usr/bin/env bash
# uninstall-linux.sh — remove the Brain wiring from a Claude Code config dir on Linux.
#
# Tested on Debian Trixie (Raspberry Pi OS) and Ubuntu 22.04.
#
# Usage:
#     ~/src/AiBrain/uninstall-linux.sh <claude-config-dir>
#
# Examples:
#     ~/src/AiBrain/uninstall-linux.sh ~/.claude-personal
#     ~/src/AiBrain/uninstall-linux.sh ~/.claude-work
#
# Reverses setup-linux.sh. Idempotent: running on a never-installed dir is a no-op.
#
# WHAT THIS TOUCHES
#   - unregisters the 'brain' user-scope MCP server from this config dir
#   - prunes Brain-owned entries from <config>/settings.json
#   - removes <config>/CLAUDE.md ONLY if it carries our managed-by marker
#     (hand-edited CLAUDE.md without the marker is left alone)
#   - removes <config>/skills/brain/ (leaves <config>/skills/ for other skills)
#   - removes <repo>/mcp-server/.venv (regenerated by re-running setup)
#
# WHAT THIS DOES NOT TOUCH
#   - the vault (Brain/user, feedback, projects, sessions, activity.md, index)
#   - ~/.cache/fastembed (shared OS-wide, harmless)
#   - the repo itself

set -euo pipefail

if [ $# -lt 1 ]; then
  echo "usage: $0 <claude-config-dir>" >&2
  echo "example: $0 ~/.claude-personal" >&2
  exit 1
fi

CLAUDE_DIR="${1/#\~/$HOME}"
REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
MCP_SERVER_DIR="$REPO_DIR/mcp-server"
VENV_DIR="$MCP_SERVER_DIR/.venv"
VENV_PYTHON="$VENV_DIR/bin/python"

# Prefer the in-repo venv python for the settings-merge script, but fall back
# to system python3 if the venv is already gone — the prune only needs stdlib json.
PY_FOR_PRUNE="$VENV_PYTHON"
if [ ! -x "$PY_FOR_PRUNE" ]; then
  if command -v python3 >/dev/null 2>&1; then
    PY_FOR_PRUNE="$(command -v python3)"
  else
    PY_FOR_PRUNE=""
  fi
fi

echo "Brain uninstall"
echo "  repo:         $REPO_DIR"
echo "  config dir:   $CLAUDE_DIR"
if [ ! -d "$CLAUDE_DIR" ]; then
  echo
  echo "NOTE: $CLAUDE_DIR does not exist — nothing to uninstall from there."
  echo "      (venv removal below still runs.)"
fi
echo

# 1. Unregister the MCP server via the claude CLI (same config-dir asymmetry as install).
echo "[1/5] unregistering brain MCP server (user scope)"
CLAUDE_BIN="${CLAUDE_BIN:-claude}"
_canonical_path() {
  if [ -d "$1" ]; then ( cd "$1" && pwd -P ); else printf '%s' "${1%/}"; fi
}
if [ "$(_canonical_path "$CLAUDE_DIR")" = "$(_canonical_path "$HOME/.claude")" ]; then
  IS_DEFAULT_TARGET=1
else
  IS_DEFAULT_TARGET=0
fi
claude_cli() {
  if [ "$IS_DEFAULT_TARGET" = "1" ]; then
    "$CLAUDE_BIN" "$@"
  else
    CLAUDE_CONFIG_DIR="$CLAUDE_DIR" "$CLAUDE_BIN" "$@"
  fi
}

if ! command -v "$CLAUDE_BIN" >/dev/null 2>&1; then
  echo "       ⚠ '$CLAUDE_BIN' not on PATH — skipping MCP unregister."
  echo "         If brain is still registered, remove it manually later:"
  if [ "$IS_DEFAULT_TARGET" = "1" ]; then
    echo "           $CLAUDE_BIN mcp remove brain --scope user"
  else
    echo "           CLAUDE_CONFIG_DIR=$CLAUDE_DIR $CLAUDE_BIN mcp remove brain --scope user"
  fi
else
  if claude_cli mcp remove brain --scope user >/dev/null 2>&1; then
    echo "       ✓ brain MCP server unregistered"
  else
    echo "       (brain was not registered; nothing to remove)"
  fi
fi

# 2. Prune Brain-owned hook entries from settings.json.
SETTINGS_FILE="$CLAUDE_DIR/settings.json"
echo "[2/5] pruning Brain hooks from $SETTINGS_FILE"
if [ ! -f "$SETTINGS_FILE" ]; then
  echo "       (no settings.json — nothing to prune)"
elif [ -z "$PY_FOR_PRUNE" ]; then
  echo "       ⚠ no python3 available to parse settings.json — leaving hooks in place." >&2
  echo "         Install Python 3 and re-run, or hand-edit $SETTINGS_FILE." >&2
else
  "$PY_FOR_PRUNE" - "$SETTINGS_FILE" "$REPO_DIR/hooks" <<'PY'
import json, sys
settings_path, brain_hooks = sys.argv[1:3]

try:
    with open(settings_path, "r", encoding="utf-8") as f:
        settings = json.load(f)
except (FileNotFoundError, json.JSONDecodeError):
    sys.exit(0)

def _is_brain_command(cmd):
    if not isinstance(cmd, str):
        return False
    return (
        "BRAIN_VAULT=" in cmd
        or brain_hooks in cmd
        or "brain-launch" in cmd.lower()
    )

existing = settings.get("hooks", {}) or {}
if not isinstance(existing, dict):
    sys.exit(0)

removed = 0
for event in list(existing.keys()):
    groups = existing.get(event) or []
    if not isinstance(groups, list):
        continue
    pruned_groups = []
    for group in groups:
        if not isinstance(group, dict):
            pruned_groups.append(group)
            continue
        inner = group.get("hooks") or []
        kept = []
        for h in inner:
            if isinstance(h, dict) and _is_brain_command(h.get("command", "")):
                removed += 1
            else:
                kept.append(h)
        if kept:
            new_group = dict(group)
            new_group["hooks"] = kept
            pruned_groups.append(new_group)
    if pruned_groups:
        existing[event] = pruned_groups
    else:
        del existing[event]

if existing:
    settings["hooks"] = existing
else:
    settings.pop("hooks", None)

with open(settings_path, "w", encoding="utf-8") as f:
    json.dump(settings, f, indent=2)
    f.write("\n")

print(f"       ✓ removed {removed} Brain-owned hook entr{'y' if removed == 1 else 'ies'}")
PY
fi

# 3. Delete CLAUDE.md only if it carries our managed-by marker.
MARKER='<!-- managed-by: ai-brain -->'
CLAUDE_MD="$CLAUDE_DIR/CLAUDE.md"
echo "[3/5] checking $CLAUDE_MD"
if [ ! -f "$CLAUDE_MD" ]; then
  echo "       (no CLAUDE.md to remove)"
elif head -n 5 "$CLAUDE_MD" | grep -Fq "$MARKER"; then
  rm -f "$CLAUDE_MD"
  echo "       ✓ removed (marker present)"
else
  echo "       ⚠ CLAUDE.md has no managed-by marker — leaving it in place."
  echo "         (If you want it gone, delete it manually: rm '$CLAUDE_MD')"
fi

# 4. Remove the brain skill, but NOT the parent skills/ directory.
SKILL_DIR="$CLAUDE_DIR/skills/brain"
echo "[4/5] removing $SKILL_DIR"
if [ -d "$SKILL_DIR" ]; then
  rm -rf "$SKILL_DIR"
  echo "       ✓ removed"
  if [ -d "$CLAUDE_DIR/skills" ] && [ -z "$(ls -A "$CLAUDE_DIR/skills" 2>/dev/null || true)" ]; then
    rmdir "$CLAUDE_DIR/skills" 2>/dev/null || true
  fi
else
  echo "       (not present)"
fi

# 5. Remove the in-repo venv — but only if no OTHER claude config dir still
#    references it. The venv is shared across every config dir setup installed
#    into; uninstalling from one dir must not break others.
echo "[5/5] removing $VENV_DIR"
if [ ! -d "$VENV_DIR" ]; then
  echo "       (not present)"
else
  STILL_USED=""
  for other in "$HOME"/.claude*; do
    [ -d "$other" ] || continue
    [ "$(_canonical_path "$other")" = "$(_canonical_path "$CLAUDE_DIR")" ] && continue
    if [ -f "$other/settings.json" ] && grep -Fq "$VENV_DIR" "$other/settings.json" 2>/dev/null; then
      STILL_USED="$other"
      break
    fi
  done
  if [ -n "$STILL_USED" ]; then
    echo "       (still referenced by $STILL_USED — leaving in place)"
    echo "       Run this script on $STILL_USED too if you want the venv gone."
  else
    rm -rf "$VENV_DIR"
    echo "       ✓ removed"
  fi
fi

echo
echo "✓ Brain uninstalled from $CLAUDE_DIR"
echo
echo "Not touched (by design):"
echo "  - your vault (Brain/user, feedback, projects, sessions, activity.md, .index/)"
echo "  - ~/.cache/fastembed (shared OS-wide embedding model cache)"
echo "  - this repo"
echo
echo "To reinstall later: $REPO_DIR/setup-linux.sh $CLAUDE_DIR <vault-path>"
