#!/usr/bin/env pwsh
# uninstall-windows.ps1 - remove the Brain wiring from a Claude Code config dir on Windows.
#
# Usage:
#     powershell -ExecutionPolicy Bypass -File C:\src\Ai-Brain\uninstall-windows.ps1 <claude-config-dir>
#
# Example:
#     powershell -ExecutionPolicy Bypass -File C:\src\Ai-Brain\uninstall-windows.ps1 `
#         "$env:USERPROFILE\.claude-personal"
#
# Reverses setup-windows.ps1. Idempotent: running on a never-installed dir is a no-op.
#
# WHAT THIS TOUCHES
#   - unregisters the 'brain' user-scope MCP server from this config dir
#   - prunes Brain-owned entries from <config>\settings.json
#   - removes <config>\CLAUDE.md ONLY if it carries our managed-by marker
#     (hand-edited CLAUDE.md without the marker is left alone)
#   - removes <config>\skills\brain\ (leaves <config>\skills\ for other skills)
#   - removes <config>\brain-launch.cmd (Windows-only generated wrapper)
#   - removes <repo>\mcp-server\.venv (regenerated by re-running setup)
#
# WHAT THIS DOES NOT TOUCH
#   - the vault (Brain\user, feedback, projects, sessions, activity.md, index)
#   - %LOCALAPPDATA%\fastembed_cache or the user's fastembed cache path
#   - the repo itself

[CmdletBinding()]
param(
  [Parameter(Mandatory=$true, Position=0)][string]$ClaudeDir
)

$ErrorActionPreference = 'Stop'

function Expand-UserPath([string]$p) {
  if ($p.StartsWith('~')) { $p = $p -replace '^~', $HOME }
  return [System.IO.Path]::GetFullPath($p)
}

$ClaudeDir    = Expand-UserPath $ClaudeDir
$RepoDir      = Split-Path -Parent $MyInvocation.MyCommand.Path
$McpServerDir = Join-Path $RepoDir 'mcp-server'
$VenvDir      = Join-Path $McpServerDir '.venv'
$VenvPython   = Join-Path $VenvDir 'Scripts\python.exe'

# Prefer the in-repo venv python for the settings-prune script; fall back to a
# system python on PATH if the venv is already gone. Only stdlib json needed.
$PyForPrune = $null
if (Test-Path $VenvPython) {
  $PyForPrune = $VenvPython
} else {
  foreach ($cand in @('py', 'python', 'python3')) {
    if (Get-Command $cand -ErrorAction SilentlyContinue) { $PyForPrune = $cand; break }
  }
}

Write-Host "Brain uninstall"
Write-Host "  repo:         $RepoDir"
Write-Host "  config dir:   $ClaudeDir"
if (-not (Test-Path $ClaudeDir)) {
  Write-Host ""
  Write-Host "NOTE: $ClaudeDir does not exist - nothing to uninstall from there."
  Write-Host "      (venv removal below still runs.)"
}
Write-Host ""

# 1. Unregister the MCP server via the claude CLI (same config-dir asymmetry as install).
Write-Host "[1/6] unregistering brain MCP server (user scope)"
$ClaudeBin = if ($env:CLAUDE_BIN) { $env:CLAUDE_BIN } else { 'claude' }
$DefaultClaudeDir = Join-Path $env:USERPROFILE '.claude'
$IsDefaultTarget = ([System.IO.Path]::GetFullPath($ClaudeDir).TrimEnd('\')) -ieq `
                   ([System.IO.Path]::GetFullPath($DefaultClaudeDir).TrimEnd('\'))

if (-not (Get-Command $ClaudeBin -ErrorAction SilentlyContinue)) {
  Write-Host "       [warn] '$ClaudeBin' not on PATH - skipping MCP unregister."
  Write-Host "         If brain is still registered, remove it manually later:"
  if ($IsDefaultTarget) {
    Write-Host "           Remove-Item Env:CLAUDE_CONFIG_DIR -ErrorAction SilentlyContinue"
  } else {
    Write-Host "           `$env:CLAUDE_CONFIG_DIR = '$ClaudeDir'"
  }
  Write-Host "           claude mcp remove brain --scope user"
} else {
  Remove-Item Env:CLAUDE_CONFIG_DIR -ErrorAction SilentlyContinue
  if (-not $IsDefaultTarget) { $env:CLAUDE_CONFIG_DIR = $ClaudeDir }
  try {
    & $ClaudeBin mcp remove brain --scope user 2>$null | Out-Null
    if ($LASTEXITCODE -eq 0) {
      Write-Host "       [ok] brain MCP server unregistered"
    } else {
      Write-Host "       (brain was not registered; nothing to remove)"
    }
  } finally {
    Remove-Item Env:CLAUDE_CONFIG_DIR -ErrorAction SilentlyContinue
  }
}

# 2. Prune Brain-owned hook entries from settings.json.
$SettingsFile = Join-Path $ClaudeDir 'settings.json'
Write-Host "[2/6] pruning Brain hooks from $SettingsFile"
if (-not (Test-Path $SettingsFile)) {
  Write-Host "       (no settings.json - nothing to prune)"
} elseif (-not $PyForPrune) {
  Write-Warning "no Python available to parse settings.json - leaving hooks in place."
  Write-Warning "Install Python 3 and re-run, or hand-edit $SettingsFile."
} else {
  $pruneScript = @'
import json, sys
settings_path, brain_hooks = sys.argv[1:3]

try:
    with open(settings_path, "r", encoding="utf-8") as f:
        settings = json.load(f)
except (FileNotFoundError, json.JSONDecodeError):
    sys.exit(0)

def _is_brain_command(cmd):
    if not isinstance(cmd, str):
        return False
    low = cmd.lower()
    return (
        "brain_vault=" in low
        or brain_hooks.lower() in low
        or "brain-launch" in low
    )

existing = settings.get("hooks", {}) or {}
if not isinstance(existing, dict):
    sys.exit(0)

removed = 0
for event in list(existing.keys()):
    groups = existing.get(event) or []
    if not isinstance(groups, list):
        continue
    pruned_groups = []
    for group in groups:
        if not isinstance(group, dict):
            pruned_groups.append(group)
            continue
        inner = group.get("hooks") or []
        kept = []
        for h in inner:
            if isinstance(h, dict) and _is_brain_command(h.get("command", "")):
                removed += 1
            else:
                kept.append(h)
        if kept:
            new_group = dict(group)
            new_group["hooks"] = kept
            pruned_groups.append(new_group)
    if pruned_groups:
        existing[event] = pruned_groups
    else:
        del existing[event]

if existing:
    settings["hooks"] = existing
else:
    settings.pop("hooks", None)

with open(settings_path, "w", encoding="utf-8") as f:
    json.dump(settings, f, indent=2)
    f.write("\n")

word = "entry" if removed == 1 else "entries"
print(f"       [ok] removed {removed} Brain-owned hook {word}")
'@
  $prunePath = Join-Path $env:TEMP "brain-uninstall-prune-$PID.py"
  [System.IO.File]::WriteAllText($prunePath, $pruneScript)
  try {
    $HooksDir = Join-Path $RepoDir 'hooks'
    & $PyForPrune $prunePath $SettingsFile $HooksDir
  } finally {
    Remove-Item -Force $prunePath -ErrorAction SilentlyContinue
  }
}

# 3. Delete CLAUDE.md only if it carries our managed-by marker.
$Marker = '<!-- managed-by: ai-brain -->'
$ClaudeMd = Join-Path $ClaudeDir 'CLAUDE.md'
Write-Host "[3/6] checking $ClaudeMd"
if (-not (Test-Path $ClaudeMd)) {
  Write-Host "       (no CLAUDE.md to remove)"
} else {
  $head = Get-Content $ClaudeMd -TotalCount 5 -ErrorAction SilentlyContinue
  if ($head -and ($head -join "`n").Contains($Marker)) {
    Remove-Item -Force $ClaudeMd
    Write-Host "       [ok] removed (marker present)"
  } else {
    Write-Host "       [warn] CLAUDE.md has no managed-by marker - leaving it in place."
    Write-Host "         (If you want it gone, delete it manually: Remove-Item '$ClaudeMd')"
  }
}

# 4. Remove the brain skill, but NOT the parent skills\ directory.
$SkillDir = Join-Path $ClaudeDir 'skills\brain'
Write-Host "[4/6] removing $SkillDir"
if (Test-Path $SkillDir) {
  Remove-Item -Recurse -Force $SkillDir
  Write-Host "       [ok] removed"
  $SkillsRoot = Join-Path $ClaudeDir 'skills'
  if ((Test-Path $SkillsRoot) -and (-not (Get-ChildItem -Force $SkillsRoot -ErrorAction SilentlyContinue))) {
    Remove-Item -Force $SkillsRoot -ErrorAction SilentlyContinue
  }
} else {
  Write-Host "       (not present)"
}

# 5. Remove the generated brain-launch.cmd (Windows-only).
$LaunchCmd = Join-Path $ClaudeDir 'brain-launch.cmd'
Write-Host "[5/6] removing $LaunchCmd"
if (Test-Path $LaunchCmd) {
  Remove-Item -Force $LaunchCmd
  Write-Host "       [ok] removed"
} else {
  Write-Host "       (not present)"
}

# 6. Remove the in-repo venv - but only if no OTHER claude config dir still
#    references it. The venv is shared across every config dir setup installed
#    into; uninstalling from one must not break others. On Windows the venv path
#    lives inside each config's brain-launch.cmd (and via that, indirectly in
#    settings.json), so check both files.
Write-Host "[6/6] removing $VenvDir"
if (-not (Test-Path $VenvDir)) {
  Write-Host "       (not present)"
} else {
  $StillUsed = $null
  $claudeCandidates = Get-ChildItem -Path $env:USERPROFILE -Directory -Filter '.claude*' -ErrorAction SilentlyContinue
  foreach ($other in $claudeCandidates) {
    $otherFull = [System.IO.Path]::GetFullPath($other.FullName).TrimEnd('\')
    $selfFull  = [System.IO.Path]::GetFullPath($ClaudeDir).TrimEnd('\')
    if ($otherFull -ieq $selfFull) { continue }
    foreach ($probe in @((Join-Path $other.FullName 'settings.json'),
                         (Join-Path $other.FullName 'brain-launch.cmd'))) {
      if (Test-Path $probe) {
        $txt = Get-Content $probe -Raw -ErrorAction SilentlyContinue
        if ($txt -and ($txt -like "*$VenvDir*")) { $StillUsed = $other.FullName; break }
      }
    }
    if ($StillUsed) { break }
  }
  if ($StillUsed) {
    Write-Host "       (still referenced by $StillUsed - leaving in place)"
    Write-Host "       Run this script on $StillUsed too if you want the venv gone."
  } else {
    Remove-Item -Recurse -Force $VenvDir
    Write-Host "       [ok] removed"
  }
}

Write-Host ""
Write-Host "[ok] Brain uninstalled from $ClaudeDir"
Write-Host ""
Write-Host "Not touched (by design):"
Write-Host "  - your vault (Brain\user, feedback, projects, sessions, activity.md, .index\)"
Write-Host "  - the fastembed model cache (shared, harmless)"
Write-Host "  - this repo"
Write-Host ""
Write-Host "To reinstall later:"
Write-Host "  powershell -ExecutionPolicy Bypass -File '$RepoDir\setup-windows.ps1' '$ClaudeDir' '<vault-path>'"
